# Generated by Django 3.0.7 on 2020-06-04 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='tutorial_slug',
            new_name='category_slug',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 12, 2, 37, 940529), verbose_name='date published.'),
        ),
    ]
